### ISSUE TITLE
Crash in weechat due to ruby exception when loading plugin

### ISSUE THREAD

**Issue by robbmanes** [appzer/pushsafer-weechat#1]
When loading the `pushsafer-weechat.rb` module, weechat crashes due to something being excepted within the plugin.

My version of weechat:
```bash
# weechat --version
3.0.1

# rpm -q weechat
weechat-3.0.1-1.fc34.x86_64
```

Getting the files directly from `weechat.org` although I have used this repositories version as well:
```bash
# curl 'https://weechat.org/files/scripts/buffzilla.rb' -o ~/.weechat/ruby/buffzilla.rb
# curl 'https://weechat.org/files/scripts/pushsafer-weechat.rb' -o ~/.weechat/ruby/pushsafer-weechat.rb
```

Within weechat, proving other ruby plugins work:
```bash
/ruby load buffzilla.rb
ruby: loading script "/root/.weechat/ruby/buffzilla.rb"
ruby: registered script "buffzilla", version 0.1 (Copy all activity to a single read-only buffer.)
```

And now loading `pushsafer-weechat.rb`:
```bash
/ruby load pushsafer-weechat.rb
```

There is a crash:
```bash
*** Very bad! WeeChat is crashing (SIGSEGV received)
*** Full crash dump was saved to /root/.weechat/weechat_crash_20210712_301467.log file.
***
*** Please help WeeChat developers to fix this bug:
***
***   1. If you have a core file, please run: gdb /path/to/weechat core
***      then issue command: "bt full" and send result to developers.
***      See the user's guide for more info about enabling the core files
***      and reporting crashes:
***      https://weechat.org/doc/stable/user#report_crashes
***
***   2. Otherwise send the backtrace (below), only if it is a complete trace.
***      Keep the crash log file, just in case developers ask you some info
***      (be careful, private info like passwords may be in this file).

======= WeeChat backtrace =======
(written by WeeChat 3.0.1, compiled on Feb 12 2021 00:00:00)
001  ??:0 [function ??]
002  ??:0 [function ??]
003  ??:? [function rb_bug_reporter_add]
004  ??:? [function ruby_sysinit]
005  ??:? [function funlockfile]
006  ??:? [function rb_check_copyable]
007  ??:? [function rb_extend_object]
008  ??:? [function rb_exc_raise]
009  ??:? [function rb_enc_raise]
010  ??:? [function rb_raise]
011  ??:? [function rb_obj_is_instance_of]
012  ??:? [function rb_convert_type_with_id]
013  ??:? [function rb_string_value]
014  ??:? [function rb_string_value_ptr]
015  ??:? [function weechat_ruby_print_exception]
016  ??:? [function weechat_ruby_exec]
017  ??:? [function weechat_ruby_api_hook_print_cb]
018  ??:0 [function ??]
019  ??:? [function weechat_ruby_load]
020  ??:? [function weechat_ruby_command_cb]
021  ??:0 [function ??]
022  ??:0 [function ??]
023  ??:0 [function ??]
024  ??:0 [function ??]
025  ??:0 [function ??]
026  ??:0 [function ??]
027  ??:0 [function ??]
028  ??:0 [function ??]
029  ??:0 [function ??]
030  ??:0 [function ??]
======= End of  backtrace =======
Aborted (core dumped)
```

I'm still debugging this further, but unsure if it is a bug in weechat, this script, or both.

**Comment by appzer** [comment]
can you post this logfile: /root/.weechat/weechat_crash_20210712_301467.log file

**Comment by robbmanes** [comment]
Did some core investigation.

```bash
# coredumpctl info
           PID: 301467 (weechat)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Mon 2021-07-12 10:40:16 EDT (6min ago)
  Command Line: weechat
    Executable: /usr/bin/weechat
 Control Group: /user.slice/user-1000.slice/session-37.scope
          Unit: session-37.scope
         Slice: user-1000.slice
       Session: 37
     Owner UID: 1000 (rmanes)
       Boot ID: 301d54b42c0c49e7907b0ed26a8de182
    Machine ID: 78d6272b447c4fa8833d808cd6ddab93
      Hostname: work.x.robbmanes.dev
       Storage: /var/lib/systemd/coredump/core.weechat.0.301d54b42c0c49e7907b0ed26>
     Disk Size: 2.7M
       Message: Process 301467 (weechat) of user 0 dumped core.     
				
				Stack trace of thread 301467:
                #0  0x00007faf116452a2 n/a (libc.so.6 + 0x3d2a2)
                #1  0x00007faf1162e8a4 n/a (libc.so.6 + 0x268a4)
                #2  0x000055e581e01cb5 weechat_shutdown.cold (weechat + 0xacb5)
                #3  0x00007faf0f62bd7a rb_bug_for_fatal_signal (libruby.so.3.0 + 0>
                #4  0x00007faf0f74b28d sigsegv (libruby.so.3.0 + 0x1cb28d)
                #5  0x00007faf11a3ea20 __restore_rt (libpthread.so.0 + 0x13a20)
                #6  0x00007faf0f63051a rb_ec_tag_jump (libruby.so.3.0 + 0xb051a)
                #7  0x00007faf0f635d12 rb_longjmp (libruby.so.3.0 + 0xb5d12)
                #8  0x00007faf0f635e72 rb_exc_raise (libruby.so.3.0 + 0xb5e72)
                #9  0x00007faf0f62d1d6 rb_vraise (libruby.so.3.0 + 0xad1d6)
                #10 0x00007faf0f62d27a rb_raise (libruby.so.3.0 + 0xad27a)
                #11 0x00007faf0f6c95af convert_type_with_id (libruby.so.3.0 + 0x14>
                #12 0x00007faf0f6ca81f rb_convert_type_with_id (libruby.so.3.0 + 0>
                #13 0x00007faf0f7669a7 rb_string_value (libruby.so.3.0 + 0x1e69a7)
                #14 0x00007faf0f76a28b rb_string_value_ptr (libruby.so.3.0 + 0x1ea>
                #15 0x00007faf0f90ef3e weechat_ruby_print_exception (ruby.so + 0xa>
                #16 0x00007faf0f90f957 weechat_ruby_exec (ruby.so + 0xb957)
                #17 0x00007faf0f91ccc4 weechat_ruby_api_hook_print_cb (ruby.so + 0>
                #18 0x000055e581e5ef0a gui_chat_printf_date_tags (weechat + 0x67f0>
                #19 0x00007faf0f910ab6 weechat_ruby_load (ruby.so + 0xcab6)
                #20 0x00007faf0f9118f6 weechat_ruby_command_cb (ruby.so + 0xd8f6)
                #21 0x000055e581e342ab input_exec_command (weechat + 0x3d2ab)
                #22 0x000055e581e34aa0 input_data (weechat + 0x3daa0)
                #23 0x000055e581e12076 command_input (weechat + 0x1b076)
                #24 0x000055e581e342ab input_exec_command (weechat + 0x3d2ab)
                #25 0x000055e581e34aa0 input_data (weechat + 0x3daa0)
                #26 0x000055e581e796bc gui_key_flush.part.0 (weechat + 0x826bc)
                #27 0x000055e581e79bbc gui_key_read_cb (weechat + 0x82bbc)
                #28 0x000055e581e0888f main (weechat + 0x1188f)
                #29 0x00007faf1162fb75 n/a (libc.so.6 + 0x27b75)
                #30 0x000055e581e0945e _start (weechat + 0x1245e)
```

The key appears to be these frames on the stack:
```bash
#15 0x00007faf0f90ef3e weechat_ruby_print_exception (ruby.so + 0xa>
#16 0x00007faf0f90f957 weechat_ruby_exec (ruby.so + 0xb957)
#17 0x00007faf0f91ccc4 weechat_ruby_api_hook_print_cb (ruby.so + 0>
#18 0x000055e581e5ef0a gui_chat_printf_date_tags (weechat + 0x67f0>
#19 0x00007faf0f910ab6 weechat_ruby_load (ruby.so + 0xcab6)
```

So it appears to me that we try to except the script for some reason that I don't know right now, and then we error just trying to print that, causing another exception within weechat.

Using one of the cores from the crash, I debugged this further in `gdb`:
```bash
# file /var/lib/systemd/coredump/core.weechat.0.301d54b42c0c49e7907b0ed26a8de182.301467.1626100816000000.zst

# zstd -d /var/lib/systemd/coredump/core.weechat.0.301d54b42c0c49e7907b0ed26a8de182.301467.1626100816000000.zst

# gdb $(which weechat) /var/lib/systemd/coredump/core.weechat.0.301d54b42c0c49e7907b0ed26a8de182.301467.1626100816000000
```

In frame 17 of the stack, we see we call `weechat_ruby_exec()` against the script to start where things go wrong:

```bash
(gdb) bt
#0  0x00007faf116452a2 in ?? () from /lib64/libc.so.6
#1  0x00007faf1162e8a4 in ?? () from /lib64/libc.so.6
#2  0x000055e581e01cb5 in weechat_shutdown (return_code=<optimized out>,
    crash=<optimized out>)
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/core/weechat.c:752
#3  0x00007faf0f62bd7a in rb_bug_for_fatal_signal ()
   from /lib64/libruby.so.3.0
#4  0x00007faf0f74b28d in sigsegv () from /lib64/libruby.so.3.0
#5  <signal handler called>
#6  0x00007faf0f63051a in rb_ec_tag_jump () from /lib64/libruby.so.3.0
#7  0x00007faf0f635d12 in rb_longjmp () from /lib64/libruby.so.3.0
#8  0x00007faf0f635e72 in rb_exc_raise () from /lib64/libruby.so.3.0
#9  0x00007faf0f62d1d6 in rb_vraise () from /lib64/libruby.so.3.0
#10 0x00007faf0f62d27a in rb_raise () from /lib64/libruby.so.3.0
#11 0x00007faf0f6c95af in convert_type_with_id ()
   from /lib64/libruby.so.3.0
#12 0x00007faf0f6ca81f in rb_convert_type_with_id ()
   from /lib64/libruby.so.3.0
#13 0x00007faf0f7669a7 in rb_string_value () from /lib64/libruby.so.3.0
#14 0x00007faf0f76a28b in rb_string_value_ptr () from /lib64/libruby.so.3.0
#15 0x00007faf0f90ef3e in weechat_ruby_print_exception (err=94444239448040)
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/plugins/ruby/weechat-ruby.c:285
#16 0x00007faf0f90f957 in weechat_ruby_exec (script=<optimized out>,
    ret_type=0, function=<optimized out>, format=<optimized out>,
    argv=<optimized out>)
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/plugins/ruby/weechat-ruby.c:518
#17 0x00007faf0f91ccc4 in weechat_ruby_api_hook_print_cb (
    pointer=<optimized out>, data=<optimized out>, buffer=0x55e58333aab0,
    date=<optimized out>, tags_count=<optimized out>, tags=0x0,
    displayed=<optimized out>, highlight=<optimized out>,
    prefix=0x55e583340784 "",
    message=0x55e5836d7a60 "ruby: loading script \"/root/.weechat/ruby/pushsafer-weechat.rb\"")
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/plugins/ruby/weechat-ruby-api.c:3190
#18 0x000055e581e5ef0a in hook_print_exec (line=0x55e5836d7ca0,
    buffer=0x55e58333aab0)
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/core/hook/wee-hook-print.c:132
#19 gui_chat_printf_date_tags_internal (message=<optimized out>, tags=0x0,
    date_printed=1626100816, date=1626100816, buffer=0x55e58333aab0)
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/gui/gui-chat.c:864
#20 gui_chat_printf_date_tags (buffer=0x55e58333aab0, buffer@entry=0x0,
    date=1626100816, date@entry=0, tags=tags@entry=0x0,
    message=<optimized out>)
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/gui/gui-chat.c:1001
#21 0x00007faf0f910ab6 in weechat_ruby_load (
    filename=filename@entry=0x55e5836d6fb0 "/root/.weechat/ruby/pushsafer-weechat.rb", code=code@entry=0x0)
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/plugins/ruby/weechat-ruby.c:612
- - - - 8< - - - -

(gdb) frame 17
#17 0x00007faf0f91ccc4 in weechat_ruby_api_hook_print_cb (
    pointer=<optimized out>, data=<optimized out>, buffer=0x55e58333aab0,
    date=<optimized out>, tags_count=<optimized out>, tags=0x0,
    displayed=<optimized out>, highlight=<optimized out>,
    prefix=0x55e583340784 "",
    message=0x55e5836d7a60 "ruby: loading script \"/root/.weechat/ruby/pushsafer-weechat.rb\"")
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/plugins/ruby/weechat-ruby-api.c:3190
3190            rc = (int *) weechat_ruby_exec (script,
```

The exception from weechat occurs in frame 16 because we're unable to load a function:

```bash
(gdb) frame 16
#16 0x00007faf0f90f957 in weechat_ruby_exec (script=<optimized out>,
    ret_type=0, function=<optimized out>, format=<optimized out>,
    argv=<optimized out>)
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/plugins/ruby/weechat-ruby.c:518
518             weechat_ruby_print_exception (err);
```

And here is that error:

```C
void *
weechat_ruby_exec (struct t_plugin_script *script,
                   int ret_type, const char *function,
                   const char *format, void **argv)
{
    VALUE rc, err;
    int ruby_error, i, argc, *ret_i;
    VALUE argv2[16];
    void *ret_value;
    struct t_plugin_script *old_ruby_current_script;

    ret_value = NULL;

    old_ruby_current_script = ruby_current_script;
    ruby_current_script = script;
- - - - 8< - - - -
    if (argc > 0)
    {
        rc = rb_protect_funcall ((VALUE) script->interpreter,
                                 rb_intern (function),
                                 &ruby_error, argc, argv2);
    }
    else
    {
        rc = rb_protect_funcall ((VALUE) script->interpreter,
                                 rb_intern (function),
                                 &ruby_error, 0, NULL);
    }

	weechat_ruby_output_flush ();

    if (ruby_error)
    {
        weechat_printf (NULL,
                        weechat_gettext ("%s%s: unable to run function \"%s\""),
                        weechat_prefix ("error"), RUBY_PLUGIN_NAME, function);

        err = rb_gv_get ("$!");
        weechat_ruby_print_exception (err);

        return NULL;
    }
```

Sadly, this function name optimized out:
```bash
(gdb) p function
$2 = <optimized out>
```

If I step back and check the previous frame, I'm surprised at what I find in there for the function:

```bash
(gdb) frame 17
#17 0x00007faf0f91ccc4 in weechat_ruby_api_hook_print_cb (
    pointer=<optimized out>, data=<optimized out>, buffer=0x55e58333aab0,
    date=<optimized out>, tags_count=<optimized out>, tags=0x0,
    displayed=<optimized out>, highlight=<optimized out>,
    prefix=0x55e583340784 "",
    message=0x55e5836d7a60 "ruby: loading script \"/root/.weechat/ruby/pushsafer-weechat.rb\"")
    at /usr/src/debug/weechat-3.0.1-1.fc34.x86_64/src/plugins/ruby/weechat-ruby-api.c:3190
3190            rc = (int *) weechat_ruby_exec (script,

(gdb) p ptr_function
$3 = 0x55e5836cca00 " \346\364\202\345U"
```

Here is the actual `weechat_ruby_api_hook_print_cb` for reference:
```C
int
weechat_ruby_api_hook_print_cb (const void *pointer, void *data,
                                struct t_gui_buffer *buffer,
                                time_t date,
                                int tags_count, const char **tags,
                                int displayed, int highlight,
                                const char *prefix, const char *message)
{
    struct t_plugin_script *script;
    void *func_argv[8];
    char empty_arg[1] = { '\0' };
    const char *ptr_function, *ptr_data;
    static char timebuffer[64];
    int *rc, ret;

    /* make C compiler happy */
    (void) tags_count;

    script = (struct t_plugin_script *)pointer;
    plugin_script_get_function_and_data (data, &ptr_function, &ptr_data);
	
    if (ptr_function && ptr_function[0])
    {
        snprintf (timebuffer, sizeof (timebuffer), "%lld", (long long)date);

        func_argv[0] = (ptr_data) ? (char *)ptr_data : empty_arg;
        func_argv[1] = (char *)API_PTR2STR(buffer);
        func_argv[2] = timebuffer;
        func_argv[3] = weechat_string_build_with_split_string (tags, ",");
        if (!func_argv[3])
            func_argv[3] = strdup ("");
        func_argv[4] = &displayed;
        func_argv[5] = &highlight;
        func_argv[6] = (prefix) ? (char *)prefix : empty_arg;
        func_argv[7] = (message) ? (char *)message : empty_arg;

        rc = (int *) weechat_ruby_exec (script,
                                        WEECHAT_SCRIPT_EXEC_INT,
                                        ptr_function,
                                        "ssssiiss", func_argv);
- - - - 8< - - - -
```

I'm not sure how the loading mechanism of weechat truly works, this is my first foray into it, but I am suspicious of how we're getting the `ptr_function` from the script.  I still don't know why this is the only plugin with that issue (so far) though.

**Comment by robbmanes** [comment]
> can you post this logfile: /root/.weechat/weechat_crash_20210712_301467.log file

Sure can, thank you for looking at this.

It's crazy big unfortunately:
```bash
# wc -l /root/.weechat/weechat_crash_20210712_301467.log
46721 /root/.weechat/weechat_crash_20210712_301467.log
```

So I instead here is a [Google Docs link](https://drive.google.com/file/d/1FwjbAN_RianlvvMw8rChcHoWyyFvLj_p/view?usp=sharing) to it; I tried pastebin but it exceeded the maximum size unfortunately

**Comment by robbmanes** [comment]
Okay, so weechat handling of ruby seems poor.

If there is any error whatsoever that raises an exception, the exception handler in *weechat* itself crashes; this doesn't exempt the plugin, but it sure means the entire instance of weechat goes down.

To prove the point, I can crash weechat by loading any ruby plugin with invalid syntax whatsoever in the same way with a similar stack.

To that end, I can raise this with weechat, while we try and find out what is incorrect about the pushsafer plugin's loading that produces an exception.

**Comment by robbmanes** [comment]
Proving the point about bad ruby handling in WeeChat, start with an intentionally bad string:
```bash
'This definitely is not how you're supposed to do this'
```

With respective language scripts:
```bash
# cat ~/.weechat/ruby/invalid-ruby-script.rb
Weechat.print('This definitely is not how you're supposed to do this')

# cat ~/.weechat/python/invalid-python-script.py
print('This definitely is not how you're supposed to do this')
```

Loading the python script doesn't crash all of weechat, the interpreter error is just forwarded on:
```bash
/python load invalid-python-script.py

"/root/.weechat/python/invalid-python-script.py"
python: stdout/stderr (?):   File
"/root/.weechat/python/invalid-python-script.py",
line 1
python: stdout/stderr (?): print('This definitely is not how you're supposed to do this')
python: stdout/stderr (?): ^
python: stdout/stderr (?): SyntaxError: invalidsyntax
python: unable to parse file "/root/.weechat/python/invalid-python-script.py"
```

And loading the ruby version crashes weechat:
```
/ruby load invalid-ruby-script.rb
- - - - 8< - - - -
======= End of  backtrace =======
Aborted (core dumped)
```

So I'll definitely bring this up with WeeChat and focus in this issue on finding what might be wrong when we're initializing with the PushSafer plugin; the crash has nothing to do with PushSafer, any ruby exception causes the crash it seems.

**Comment by robbmanes** [comment]
Okay, so a later version of WeeChat solves the ruby crashing issue.  I tested on 3.2 and now it just works entirely:
```bash
 ruby: registered script "pushsafer-weechat", version
 0.1 (Send highlights and private messages in channels
 to your Android, Windows 10 or IOS device via
 Pushsafer)
```

Apparently 3.0=>3.2 have a large number of ruby improvements, so this was 100% a weechat bug.  Thanks!

**Comment by appzer** [comment]
great to hear that all works fine!
Regards Kevin

**Comment by robbmanes** [comment]
Let this issue forever stand as a testament to "over-thinking the problem", and that sometimes "just upgrade your version" is exactly the right answer.
